version: '3.8'


volumes:
  postgres:

services:
  postgresdb:
    container_name: postgresdb
    image: postgres:15.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      PGDATA: /data/postgres
      POSTGRES_DB: tinkoff-tusich
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

#  tinkoff-tusich:
#    image: docker.io/library/wk
#    environment:
#      DB_URL: postgresdb
#      DB_USER: postgres
#      DB_PASS: pass1234
#      DB_NAME: tinkoff-tusich
#    ports:
#      - "1234:1234"
#    depends_on:
#      - postgresdb
